const CartActionType = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    INCREASE_ITEM_IN_CART: "INCREASE_ITEM_IN_CART",
    REDUCE_ITEM_QUATITY: "REDUCE_ITEM_QUATITY",

    MAHNDRA_NAME: "MAHNDRA_NAME"
}


export default CartActionType 